docs: Updated Ingress and Istio manifests to support Openshift 3.11
keptn/keptn.github.io pull request #1011
Opened 2022-01-14 09:24 UTC by odubajDT

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

Fixes https://github.com/keptn/keptn/issues/4407

2022-01-17 06:21 UTC, oleg-nenashev requested changes
Maybe it is time to deprecate documentation for old versions. Subject for a rework later. This change LGTM, but 0.x.12 docs also need to be updated after https://github.com/keptn/keptn.github.io/pull/1009

2022-01-17 06:36 UTC, odubajDT commented
> Maybe it is time to deprecate documentation for old versions. Subject for a rework later. This change LGTM, but 0.x.12 docs also need to be updated after #1009

Sure, we can keep this open and after merging #1009, we will adapt the changes

2022-01-17 11:53 UTC, thisthat commented
#1009 is merged, @odubajDT  you can rebase against master and edit the docs for 0.12.x 
When we release 0.12.x, we will remove 0.8.7 from the list of versions.

2022-01-17 12:08 UTC, odubajDT commented
> #1009 is merged, @odubajDT you can rebase against master and edit the docs for 0.12.x When we release 0.12.x, we will remove 0.8.7 from the list of documented versions.

Updated

2022-01-18 11:00 UTC, mowies requested changes

2022-01-18 11:00 UTC, mowies commented on content/docs/0.10.x/operate/install/index.md
> +    * Istio provides an Ingres Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```suggestion
    * Istio provides an Ingress Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.10.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.10.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.9.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.9.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.8.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.8.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.8.x/operate/install/index.md
> +    * Istio provides an Ingres Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```suggestion
    * Istio provides an Ingress Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.12.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.12.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.12.x/operate/install/index.md
> +    * Istio provides an Ingres Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```suggestion
    * Istio provides an Ingress Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.11.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.11.x/operate/install/index.md
> +    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example of an `ingress-manifest.yaml
```suggestion
    * Create an `ingress-manifest.yaml` manifest for an Ingress object in which you set IP-ADDRESS or your hostname and then apply the manifest. (**Note:** In the example below, `nip.io` is used as wildcard DNS for the IP address.)
```

2022-01-18 11:00 UTC, mowies commented on content/docs/0.11.x/operate/install/index.md
> +    * Istio provides an Ingres Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```suggestion
    * Istio provides an Ingress Controller. To install Istio, please refer to the [official documentation](https://istio.io/latest/docs/setup/install/).
```

2022-01-18 11:21 UTC, odubajDT commented
@mowies thank you, fixed :)

2022-01-18 11:58 UTC, mowies approved these changes

2022-01-18 12:36 UTC, merged