docs: Manage OpenID session secrets
keptn/keptn.github.io pull request #1025
Opened 2022-02-02 14:09 UTC by Kirdock

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

2022-02-03 06:51 UTC, thisthat approved these changes

2022-02-03 06:51 UTC, thisthat commented on content/docs/0.13.x/operate/user_management/oauth_secrets/index.md
> +In this section, the management of the session and database encryption secret of the Keptn Bridge is explained.
```suggestion
In this section, the management of the session and database encryption secrets of the Keptn Bridge is explained.
```

2022-02-03 06:51 UTC, thisthat commented on content/docs/0.13.x/operate/user_management/oauth_secrets/index.md
> +* Re-start the Keptn Bridge since it requires new secrets:
```suggestion
* Re-start the Keptn Bridge to fetch the new secrets:
```

2022-02-03 08:17 UTC, StackScribe commented on content/docs/0.13.x/operate/user_management/oauth_secrets/index.md
> +In this section, the management of the session and database encryption secrets of the Keptn Bridge is explained.
```suggestion
This section explains the management of the session and database encryption secrets of the Keptn Bridge.
```

2022-02-03 08:20 UTC, StackScribe commented on content/docs/0.13.x/operate/user_management/oauth_secrets/index.md
> +- `database encryption secret`: This secret is used to encrypt the session in the database.
```suggestion
- `session secret`: Used to hash the session of the user.
- `database encryption secret`: Used to encrypt the session in the database.
```
"This secret is" in these two items seems like superfluous noise but you may disagree.

2022-02-03 08:22 UTC, StackScribe commented on content/docs/0.13.x/operate/user_management/oauth_secrets/index.md
> +    * To generate the secrets, use the following commands and store them into the environment variables `OAUTH_SESSION_SECRET` and `OAUTH_DATABASE_ENCRYPT_SECRET`:
```suggestion
    * Use the following commands to generate the secrets and store the results into the environment variables `OAUTH_SESSION_SECRET` and `OAUTH_DATABASE_ENCRYPT_SECRET`:
```
The existing syntax says that one is storing the commands in the environment variables and I don't think that is the intent.

2022-02-03 12:10 UTC, StackScribe reviewed
lgtm

2022-02-12 08:54 UTC, oleg-nenashev requested changes
Looks good to me. No blockers in spelling check, but we need to configure the bot exceptions so that the master branch remains green

2022-02-14 07:58 UTC, oleg-nenashev approved these changes
+1 from me since the bot is disabled

2022-02-14 10:37 UTC, merged