Patch/clarify webhook
keptn/keptn.github.io pull request #1041
Opened 2022-02-14 20:55 UTC by robertjahn

2022-02-14 20:58 UTC, robertjahn commented
This will also address https://github.com/keptn/keptn.github.io/issues/1037

2022-02-15 05:25 UTC, oleg-nenashev reviewed
The addition to the main page looks nice! Just a style thing, maybe it makes sense to split long paragraphs to multiple lines like it was in the original content. It is useful for code reviews and for incremental pull requests.

I also wonder about removing the Jenkins webhook example. It seems to be a nice addition if this is still relevant. Should it be rather moved to Tutorials and referenced from there? Same for Slack that it rather on ArtifactHub now

2022-02-16 08:23 UTC, oleg-nenashev requested changes
Requesting changes to indicate there is a discussion to be done @robertjahn

2022-02-17 04:17 UTC, agardnerIT commented
More than happy to be overruled but I have a problem with the `interactive` and `non interactive` webhook terminology. The first time I heard those terms I thought **I** had to interact to do something.

Perhaps add some text like: "If you would like a third party too to **act**, you most likely want to subscribe to the `.triggered` event to trigger your external tool. In this case, the external tool is responsible for sending a `.started` and `.finished` event back to Keptn.
If you want to notify a tool that something has occurred (for example notify a messaging platform) , you'd usually subscribe to a `.finished` event. In this case, the integration is fire-and-forget so you don't need to send any other events."

2022-02-17 15:20 UTC, grabnerandi commented
Chiming in on the discussion regarding interactive and non-interactive. How about "active" and "passive" integrations? Active means that the integration actively applies some changes to the environment, e.g: deploy, execute a test, ... -> passive on the other hand is just consuming the data without changing the impact of the sequence flow.
besides active & passive you could also use "Actor" & "Consumer"

Just my thoughts as a non-native speaker that also thinks that interactive and non-interactive sounds a bit weird

2022-02-18 20:30 UTC, robertjahn commented
I agree the name should be easy to refer to and clear what is means.  Some options.  I am leaning towards the one with stars because they do describe better how they work, but they are kinda long in the name.

ONEWAY
a) Asynchronous
b) unidirectional
c) fire-and-forget *
d) silent
e) non-interactive
f) passive
g) broadcast

TWOWAY
a) Synchronous
b) request-response
c) Synchronous request-response *
d) bidirectional
e) interactive
f) active

here is a good references I found for pattern types: https://docs.oracle.com/cd/E23943_01/doc.1111/e17363/chapter05.htm#FPCON244 
https://www.enterpriseintegrationpatterns.com/patterns/conversation/BasicIntro.html

2022-02-21 10:19 UTC, miigwi commented
I like the "active" / "passive" differentiation for the webhook integrations. Gives a better picture than "interactive" and "non-interactive".

2022-02-21 12:32 UTC, johannes-b commented
I like the idea @grabnerandi was proposing: differentiation between *active* and *passive*. 
These two terms are short, precise, and bring it to the point.

2022-02-23 20:25 UTC, robertjahn commented
ok seem to be consensus on active and passive.  I have adjusted accordingly in my last commit

2022-02-25 14:56 UTC, johannes-b commented
@robertjahn please do not delete: content/docs/0.13.x/integrations/webhooks/jenkins/index.md 
We still need it since there is no Jenkins example on the ArtifactHub for Jenkins: 
![image](https://user-images.githubusercontent.com/729071/155736703-a8ff4ea7-a39b-4a9e-95a9-8781f547018a.png)

2022-02-25 15:09 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +Depending on the receiving tools configuration requirements, data can be either passed within the payload body or as query params in the URL along with any required headers and API tokens.
Should be: "... receiving tool's configuration ..."

2022-02-25 15:09 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +Webhook configurations, referred to as subscriptions, are created at a *Task* level and are configured to listen to one of the the following task [event types](https://github.com/keptn/spec/blob/0.2.
Remove: ~~the~~ the following

2022-02-25 15:09 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +* *Task suffix*: The state of the task when the webhook should be fired; select one of: `started`, of `finished`
`, of finished ` should be  `, or finished`

2022-02-25 15:09 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +The `Send finished` event flag is not applicable to a *non-interative* webhook. So you can leave it unselected as shown below.
Please change `non-interactive` to `passive`

2022-02-25 15:09 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +**Step 2: third-party webhook receiver**
third-party > Third-party

2022-02-25 15:12 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +1. Ensure that that the `Automatically` option is selected as shown below. When this is set, the webhook service will automatically send the task `finished` event for your subscription.
Ensure ~~that~~ that

2022-02-25 15:12 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +* If the third-party webhook receiver does NOT send back the task `finished` event, the sequence will remain in a waiting states and will not continue until it times out or the it receives the task `
.. in a waiting states ... > in a waiting state

2022-02-25 15:12 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +* If the third-party webhook receiver does NOT send back the task `finished` event, the sequence will remain in a waiting states and will not continue until it times out or the it receives the task `
... or ~~the~~ it receives the task ...

2022-02-25 15:12 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +1. Ensure that that the `By webhook receiver` option is selected as shown below. When this is set, the webhook service will expect the webhook receiver to send back the task `finished` event.
Ensure ~~that~~ that

2022-02-25 15:12 UTC, johannes-b commented on content/docs/0.13.x/integrations/webhooks/_index.md
> +This custom data will be automatically appended to every remaining `triggered` task event in the sequence.  The data much be passed in a attribute with the name of the task.
.. passed in a**n** attribute ...

2022-02-25 16:49 UTC, robertjahn commented
> @robertjahn please do not delete: content/docs/0.13.x/integrations/webhooks/jenkins/index.md We still need it since there is no Jenkins example on the ArtifactHub for Jenkins: ![image](https://user-images.githubusercontent.com/729071/155736703-a8ff4ea7-a39b-4a9e-95a9-8781f547018a.png)

@johannes-b  -- I put Jenkins back.  But I removed the slack page.  But to make jenkins not so lonely at the top of the page, I added an examples subpage.  
<img width="749" alt="image" src="https://user-images.githubusercontent.com/24907089/155754400-f503c631-0a33-478f-8266-89fcbea984cc.png">

2022-02-28 08:18 UTC, johannes-b approved these changes
lgtm

2022-02-28 20:14 UTC, oleg-nenashev approved these changes
LGTM, thanks for the patches!

2022-02-28 20:14 UTC, merged