Add instructions to sync for with master; change title
keptn/keptn.github.io pull request #1083
Opened 2022-03-09 09:28 UTC by StackScribe

Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>

* Add instructions to regularly sync fork with master
* Changed title to include "documentation" string

2022-03-09 09:40 UTC, johannes-b approved these changes
lgtm

2022-03-10 16:27 UTC, oleg-nenashev requested changes
Wrong title. This is a guide for the entire website, not just for the docs section

2022-03-10 16:27 UTC, oleg-nenashev commented on CONTRIBUTING.md
> +# Contribute to the Keptn documentation
Revert?

2022-03-13 05:54 UTC, StackScribe commented on CONTRIBUTING.md
> +# Contribute to the Keptn documentation
```suggestion
# Contribute to the Keptn website
```

2022-03-13 17:38 UTC, oleg-nenashev approved these changes

2022-03-13 17:40 UTC, merged