Created 'Files' subsection in reference section
keptn/keptn.github.io pull request #1102
Opened 2022-03-12 05:15 UTC by Ciggzy1312

Signed-off-by: Deepayan <deepayanmukherjee1312@gmail.com>

Moved sli slo sli-provider to files subsection in reference section

2022-03-13 00:21 UTC, StackScribe reviewed
I think this looks good and we need to do this step first so we can start adding other file reference pages to the set.

One caveat: we may need to modify the metrics field in the index.md file for each of these.  They have values like 10 and 15 and s falls pretty late in the alphabet.  I almost wonder if we want to start a much larger range -- maybe give these 7xx values so we have plenty of room to maneuver.  wdyt?

2022-03-15 10:26 UTC, johannes-b commented
Hi @Ciggzy1312, 

thanks for the PR. Please take into account that there is already a folder for the upcoming `0.14.x` release. Hence I would like to ask you to perform the same changes in `0.14.x` (https://github.com/keptn/keptn.github.io/tree/master/content/docs/0.14.x) as well to not lose them in the future. Thanks!

FYI: @StackScribe

2022-03-24 16:04 UTC, oleg-nenashev commented
Time to merge. I do not see external links

2022-03-28 10:40 UTC, StackScribe commented
I agree that it's time to merge this.  I'm thinking that we should merge the change only into 0.14.x, no 0.13.x.  Then we can build up this section and roll it out when 0.14.x is released.  We need to make sure we catch xrefs to these files and so forth.

2022-04-05 10:01 UTC, StackScribe requested changes

2022-04-05 10:01 UTC, StackScribe commented on content/docs/0.14.x/reference/files/_index.md
> +description: Definition of SLIs/SLOs of quality gate and how to customize them.
```suggestion
description: Reference pages for Keptn files.
```
The sli/slo pages are only the beginning here.  This section will soon include pages for many other files.

2022-04-05 12:46 UTC, StackScribe commented
I can't get into the slo/index.md and sli/index.md files to see what the weight value is but, if it is unchanged from the weight used when these files were in the quality_gates tree, I think the values are way too low.  This is the beginning of a new section that is going to end up with a lot of files that need to be listed alphabetically and "s" falls fairly late in the alphabet...  Can someone check/fix this?

2022-04-06 07:09 UTC, oleg-nenashev approved these changes

2022-04-06 07:09 UTC, merged