Recommend "Explore Keptn" exercise in QuickStart
keptn/keptn.github.io pull request #1274
Opened 2022-06-22 09:28 UTC by StackScribe

Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>

As discussed in the 22 June 2022 Community Meeting, we have published the Kilrcoda "Explore Keptn" exercise in the doc set but, for now, need to retain the old QuickStart.  This PR adds a note at the top of QuickStart recommending that people use the "Explore Keptn" exercise instead.

2022-06-22 09:35 UTC, agardnerIT commented
LGTM

2022-06-22 09:35 UTC, agardnerIT approved these changes

2022-06-22 12:58 UTC, afzal442 requested changes

2022-06-23 01:31 UTC, StackScribe commented on content/docs/quickstart/_index.md
> +That exercise  uses [KillerCoda](https://killercoda.com/)
Neither of those URLs work.  I did find playgrounds but I also found "areas" and Keptn is even listed there so I chose that one.  What do you think?  I can change it again with about two minutes effort ;-)

2022-06-23 06:17 UTC, afzal442 approved these changes

2022-06-24 06:13 UTC, agardnerIT commented
FYI, I got some answers back from the Killercoda team:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/26523841/175473877-2f0c2091-a4f3-4c66-8cd1-e7da9e78f16a.png">

2022-06-24 08:47 UTC, agardnerIT commented
What is outstanding here before merging?

2022-06-27 09:06 UTC, merged