docs: Upgrade instructions for 0.17
keptn/keptn.github.io pull request #1286
Opened 2022-06-30 12:08 UTC by mowies

### This PR
- adds instructions on how to upgrade from Keptn 0.16.x to 0.17.0

2022-07-01 09:18 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +Additionally, the Keptn Helm chart was refactored heavily to make it ready for future features and structural changes.
```suggestion
Additionally, the Keptn Helm chart has  been refactored heavily to make it ready for future features and structural changes.
```

2022-07-01 09:24 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +[Helm installation instructions](../install/#install-keptn).
```suggestion
[Helm installation instructions](../install/#helm-install).
```

2022-07-01 09:24 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +- Follow [Keptn's backup instructions](../backup_and_restore)
```suggestion
- Follow [Keptn's backup instructions](../../0.17.x/operate/backup_and_restore)
```

2022-07-01 09:24 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +- Make sure you are connected to the kubernetes cluster where Keptn is installed.
```suggestion
- Make sure you are connected to the Kubernetes cluster where Keptn is installed.
```

2022-07-01 09:25 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +- Make sure you are connected to the kubernetes cluster where Keptn is installed.
```suggestion
- Make sure you are connected to the Kubernetes cluster where Keptn is installed.
```

2022-07-01 09:26 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +- Make sure you are connected to the kubernetes cluster where Keptn is installed.
```suggestion
- Make sure you are connected to the Kubernetes cluster where Keptn is installed.
```

2022-07-01 09:26 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +   For namespace `keptn-test` and release name `keptn` (the default release name) the command would look like this:
```suggestion
   For namespace `keptn-test` and release name `keptn` (the default release name), the command would look like this:
```

2022-07-01 09:28 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +- Make sure you are connected to the kubernetes cluster where Keptn is installed.
```suggestion
- Make sure you are connected to the Kubernetes cluster where Keptn is installed.
```

2022-07-01 09:28 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +  For namespace `exec-plane` and release name `helm-service` (the default release name) the command would look like this:
```suggestion
  For namespace `exec-plane` and release name `helm-service` (the default release name), the command would look like this:
```

2022-07-01 09:32 UTC, StackScribe requested changes
I fixed a couple broken xrefs and made some editorial changes for your consideration.  The xrefs need to be fixed or the PR doesn't pass CI ;-). The others are optional.

2022-07-04 13:14 UTC, oleg-nenashev approved these changes
LGTM

2022-07-06 01:28 UTC, StackScribe commented on content/docs/install/access/index.md
> +Depending on whether you would like to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```suggestion
If you want to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```

2022-07-06 01:29 UTC, StackScribe commented on content/docs/install/access/index.md
>  1. **Install Keptn:** For installing Keptn on your cluster, please use the Helm CLI.
```suggestion
1. **Install Keptn:** Use the Helm CLI to install Keptn on your cluster.
```

2022-07-06 01:31 UTC, StackScribe commented on content/docs/install/access/index.md
>  1. **Install Keptn:** For installing Keptn on your cluster, please use the Keptn CLI.
```suggestion
1. **Install Keptn:** Use the Keptn CLI to install Keptn on your cluster.
```

2022-07-06 01:32 UTC, StackScribe commented on content/docs/install/access/index.md
> +Depending on whether you would like to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```suggestion
If you want to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```

2022-07-06 01:33 UTC, StackScribe commented on content/docs/install/access/index.md
>  1. **Install Keptn:** For installing Keptn on your cluster, please use the Keptn CLI.
```suggestion
1. **Install Keptn:** Use the Keptn CLI to install Keptn on your cluster.
```

2022-07-06 01:33 UTC, StackScribe commented on content/docs/install/access/index.md
> +Depending on whether you would like to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```suggestion
If you want to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```

2022-07-06 01:34 UTC, StackScribe commented on content/docs/install/access/index.md
>  1. **Install Keptn:** For installing Keptn on your cluster, please use the Keptn CLI.
```suggestion
1. **Install Keptn:** Use the Keptn CLI to install Keptn on your cluster.
```

2022-07-06 01:34 UTC, StackScribe commented on content/docs/install/access/index.md
> +Depending on whether you would like to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```suggestion
If you want to install the execution plane for continuous delivery, add the flag `continuousDelivery.enabled=true`.
```

2022-07-06 01:38 UTC, StackScribe commented on content/docs/install/upgrade/index.md
> +With Keptn 0.17.x, the Keptn CLI commands for `install`, `uninstall` and `upgrade` were deprecated. We recommend to upgrade using the Helm CLI instead.
```suggestion
With Keptn 0.17.x, the Keptn CLI commands for `install`, `uninstall` and `upgrade` were deprecated. We recommend that you instead use the Helm CLI to upgrade.
```
Is this really a recommendation, implying that they have other options?  Maybe it should say, "Instead, use the Helm CLI to upgrade."

2022-07-06 01:45 UTC, StackScribe commented on content/docs/install/manual-install/index.md
> +    helm install keptn keptn/keptn -n keptn --version=$KeptnVersion --create-namespace --set=continuousDelivery.enabled=true
Actually, I think this file will be deleted by https://github.com/keptn/keptn.github.io/pull/1287 .  Is that correct?  I guess we can look at everything after we merge everything and adjust accordingly

2022-07-06 01:46 UTC, StackScribe approved these changes
Looks good!  I suggested a couple of prose-tightening edits that you may use or discard but this is a nice piece of work!

2022-07-06 05:51 UTC, merged