Klc banner updates
keptn/keptn.github.io pull request #1482
Opened 2022-10-24 20:15 UTC by oleg-nenashev

I got a request to remove the carousel in favor of the news list header, and hence I implemented so. LGTM for me on the desktop, narrow and mobile screens. Keeping the carousel code for the future

![image](https://user-images.githubusercontent.com/3000480/197620078-886b2725-3716-4607-a945-e5b397aad33b.png)

2022-10-24 20:30 UTC, AloisReitbauer requested changes
Can we move the partial announcement block back to the top. Also blue on blue is very hard to read.

2022-10-24 21:04 UTC, oleg-nenashev commented
> Can we move the partial announcement block back to the top.

@AloisReitbauer  It requires more changes in Javascript and CSS. The website does not use standard controls for that from Hugo templates, and there is a collision between the header and the announcement layout once you make the text longer than one line. May need a few hours to get it sorted, will try to do it today

>  Also blue on blue is very hard to read.

Can do. We just use such rendering for links elsewhere too

2022-10-25 05:19 UTC, StackScribe commented on layouts/partials/announcement.html
> +          <li>Keptn 0.19.1 is available! Find all <a href="./docs/news/release_announcements/keptn-0191/">details on this release here</a>.
```suggestion
          <li>Keptn 0.19.1 is available! Find <a href="./docs/news/release_announcements/keptn-0191/">details here</a>.
```

2022-10-25 05:20 UTC, StackScribe approved these changes
I like it!  I made one editorial change for your consideration.

2022-10-25 11:32 UTC, merged