[WIP] Make Killercoda exercise the LTS Quick Start
keptn/keptn.github.io pull request #1502
Opened 2022-11-03 11:08 UTC by StackScribe

Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>

* Give the "Quick Start" title to the Killercoda End-to-End exercise
* Replace installation instructions in that section with links to the appropriate documentation.  The instructions that are here are not adequate and having duplicate installation instructions throughout the doc set creates maintenance headaches
* Modify the "Installation" section to make it friendly for people installing a private Keptn instance for study and demos, as well as for people installing a Keptn production instance.

Note that this PR does not update the exercise to use Keptn 1.0.x-LTS.  That will be done in a separate PR.

https://github.com/keptn/keptn.github.io/issues/1464

2022-11-03 17:45 UTC, afzal442 commented on content/docs/1.0.x/install/k8s/index.md
> +*Hint* Be sure to check [Kubernetes support & Cluster size](../k8s-support)
```suggestion
**Note:** Make sure to check [Kubernetes support & Cluster size](../k8s-support)
```

2022-11-03 17:50 UTC, afzal442 requested changes

2022-11-03 17:50 UTC, afzal442 commented on content/docs/1.0.x/install/k8s/index.md
> +  See [Check resources](../troubleshoting/#check-resources) for more information.
```suggestion
  See [Check resources](../troubleshooting/#check-resources) for more information.
```

2022-11-03 22:15 UTC, StackScribe commented on content/docs/1.0.x/install/k8s/index.md
> +*Hint* Be sure to check [Kubernetes support & Cluster size](../k8s-support)
done

2022-11-03 22:15 UTC, StackScribe commented on content/docs/1.0.x/install/k8s/index.md
> +  See [Check resources](../troubleshoting/#check-resources) for more information.
Done (blushing) ;-)

2022-11-04 02:29 UTC, agardnerIT approved these changes

2022-11-04 02:30 UTC, merged