Use keptn-mongo in command to correct permissions on OpenShift
keptn/keptn.github.io pull request #1582
Opened 2023-01-27 14:04 UTC by StackScribe

Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>

https://github.com/keptn/keptn.github.io/issues/1581

2023-01-29 21:38 UTC, eemrdog requested changes
Instead of the image name, deployment name needs to be changed to "deployment/keptn-mongo"

2023-01-30 10:22 UTC, mowies commented on content/docs/1.0.x/install/troubleshooting/index.md
> +   mongodb=keptn-mongo/mongodb-privileged:latest -n keptn
please change this to
```
kubectl set image deployment/keptn-mongo \
  mongodb=keptn/mongodb-privilged:latest -n keptn
```

2023-01-30 10:33 UTC, StackScribe commented on content/docs/1.0.x/install/troubleshooting/index.md
> +   mongodb=keptn-mongo/mongodb-privileged:latest -n keptn
done

2023-01-30 10:36 UTC, mowies approved these changes

2023-01-30 10:45 UTC, merged