docs: Changed background color for better readability
keptn/keptn.github.io pull request #1614
Opened 2023-03-02 07:29 UTC by DivyanshuSonwal

The background color of code snippets was black across various pages in [keptn](https://keptn.sh/) website making it harder to read for viewers.
This pull request fixes the readability issues by changing the background color. #1611 

![Screenshot_20230302_125516](https://user-images.githubusercontent.com/101584315/222359860-06d0580f-96e2-4413-b0aa-8998eae665cb.png)

2023-03-02 08:22 UTC, DivyanshuSonwal commented
I have created a PR for issue #1611. Can you please review it @thisthat @thschue @mowies @StackScribe?

2023-03-02 12:34 UTC, mowies requested changes
Added a few comments. Why did you change so many indentations?

2023-03-02 12:34 UTC, mowies commented on content/docs/0.15.x/operate/install/index.md
> +      ```
please replace `console` with `shell` instead of removing it wherever applicable

2023-03-02 12:34 UTC, mowies commented on content/docs/1.0.x/concepts/automated_operations/index.md
> +```
please leave the `yaml` annotations in place

2023-03-02 12:34 UTC, mowies commented on content/docs/install/access/index.md
> +2. **Get Keptn endpoint:**  Get the EXTERNAL-IP of the `api-gateway-nginx` using the command below. The Keptn API endpoint is: `http://<ENDPOINT_OF_API_GATEWAY>/api`
this is a markdown convention, please leave it in place. enumerations are always done with `1. `
```suggestion
1. **Get Keptn endpoint:**  Get the EXTERNAL-IP of the `api-gateway-nginx` using the command below. The Keptn API endpoint is: `http://<ENDPOINT_OF_API_GATEWAY>/api`
```

2023-03-02 12:34 UTC, mowies commented on content/docs/install/access/index.md
> +2. **Get Keptn endpoint:** Get the mapped port of the `api-gateway-nginx` using the command below.
this is a markdown convention, please leave it in place. enumerations are always done with `1. `
```suggestion
1. **Get Keptn endpoint:** Get the mapped port of the `api-gateway-nginx` using the command below.
```

2023-03-02 12:34 UTC, mowies commented on content/docs/install/access/index.md
> +2. **Install an Ingress-Controller and create an Ingress:**
```suggestion
1. **Install an Ingress-Controller and create an Ingress:**
```

2023-03-02 12:34 UTC, mowies commented on content/docs/install/access/index.md
> +3. **Get Keptn endpoint:** Get the HOST of the `api-keptn-ingress` using the command below. The Keptn API endpoint is: `http://<HOST>/api`
```suggestion
1. **Get Keptn endpoint:** Get the HOST of the `api-keptn-ingress` using the command below. The Keptn API endpoint is: `http://<HOST>/api`
```

2023-03-02 12:34 UTC, mowies commented on content/docs/install/access/index.md
> +2. **Setup a Port-Forward:** Configure the port-forward by using the command below.
```suggestion
1. **Setup a Port-Forward:** Configure the port-forward by using the command below.
```

2023-03-02 12:34 UTC, mowies commented on content/docs/install/access/index.md
> +3. **Get Keptn endpoint:**
```suggestion
1. **Get Keptn endpoint:** 
```

2023-03-02 12:55 UTC, mowies commented
@DivyanshuSonwal 
Maybe i misunderstood the point of this PR.
If the code block annotations are causing the block to be rendered with dark background, maybe we should change the styling instead of removing the annotations?

2023-03-02 13:07 UTC, DivyanshuSonwal commented
> @DivyanshuSonwal Maybe i misunderstood the point of this PR. If the code block annotations are causing the block to be rendered with dark background, maybe we should change the styling instead of removing the annotations?

@mowies The dark background is caused because of the formats associated like console, shell, yaml, json, etc., and by removing them the background is changed to white. Adding shell or bash instead of console is not solving the issue, it remains the same and that is why I have removed all consoles.

2023-03-04 14:34 UTC, DivyanshuSonwal commented
Can anyone update me on what needs to be done? If I have to put console, yaml, and other annotations back in place, I need an alternative to change the black background because I can't find any other way of doing so rather than removing annotations.
@DavidPHirsch @johannes-b @mowies

2023-03-06 06:50 UTC, mowies commented
You can change the CSS styling for those types of code blocks. I don't specifically know how it works, but you can probably check the docs of our docs site theme.
Our theme is called: `hugo-serif-theme`

2023-03-06 08:14 UTC, DivyanshuSonwal commented
> You can change the CSS styling for those types of code blocks. I don't specifically know how it works, but you can probably check the docs of our docs site theme. Our theme is called `hugo-serif-theme` and generally we use Hugo as a site generator with some extra style files that you can find in our docs repo as well.

Thanks, I will check the docs and try to solve this.

2023-03-07 02:19 UTC, StackScribe commented
Thanks everyone.  I confess that i removed a lot of the "console" and "yaml" strings for exactly this reason.  I had some that rendered with dark background on my local builds and light background on the published site, too.  @DivyanshuSonwal , thanks for bringing this up.  Let's figure out the right thing to do.  @aepfli , any advice?

2023-03-07 07:49 UTC, aepfli commented
removing context and the possibility of proper language specific highlight is worse, in my opinion than a styling issue. The styling issue is a visible nature, the removal of the code type in the fences removes logic.

If we want to fix/address this, we would need to take a look at the CSS styling, and fix it there, rather than removing context

2023-03-07 14:12 UTC, DivyanshuSonwal commented
> actually:
> 
> https://github.com/keptn/keptn.github.io/blob/31ab3546c56d02ae06a297ce38840a7273aa03a1/assets/scss/pages/_doc.scss#L229
> 
> changing this to
> ```
> background: $preBlockBackgroundColor !important;
> ```
> 
> should do the trick

Thanks😄.

2023-03-07 19:00 UTC, DivyanshuSonwal commented
I have performed all the required changes i.e. changed the background color for better readability of the docs. Also, I have placed all the annotations and indentations back in place as @mowies initially requested. Thank you @aepfli @StackScribe @mowies for the kind help 🙌.
Please review it now.

2023-03-08 07:06 UTC, aepfli approved these changes
thank you, lgtm

2023-03-08 11:50 UTC, mowies approved these changes
LGTM, thanks for taking care of all the changes :)

2023-03-08 12:04 UTC, merged