docs(installer): add ingress documentation for control plane helm chart
keptn/keptn.github.io pull request #915
Opened 2021-09-23 09:56 UTC by bradmccoydev

This documentation is to update values of the helm chart of the Keptn Control Plane (installer)

Closes https://github.com/keptn/keptn/issues/5297

Related PR to keptn/keptn: PR  #5315

@mowies @thisthat 

Also updated the mongodb example to say enabled as doesnt make sense for it to be not enabled and then the other values for mongo set.

Signed-off-by: bradmccoydev <bradmccoydev@gmail.com>

2021-09-23 11:30 UTC, mowies requested changes
LGTM except for the comment I left

2021-09-23 11:30 UTC, mowies commented on content/docs/0.9.x/operate/advanced_install_options/index.md
> +--set=control-plane.mongodb.enabled=true,
Please revert this to `false`. When installing keptn with an external MongoDB we don't want to install our internal MongoDB, so it makes sense that this option is disabled here.

2021-09-23 13:11 UTC, bradmccoydev commented
Thanks reverted back

2021-09-23 13:27 UTC, mowies approved these changes
LGTM 👍🏼

2021-09-23 14:45 UTC, mowies commented
Hey @bradmccoydev !
I created a new branch where documentation for the next version of keptn will be prepared (`next-version-preparations`). In there, I created a new folder `content/docs/0.10.x`.

I already switched the target of this PR to point to that branch.
Could you please move you additions to that new subfolder?
Then we can nicely release the docs together with the new features in the next version of keptn.

2021-09-24 07:55 UTC, bradmccoydev commented
@mowies Ok, I have done the following
- git remote add upstream git@github.com:keptn/keptn.github.io.git
- git pull upstream next-version-preparations
- Moved new ingress documentation from 0.9.x to 0.10.x
- Run Hugo server and tested all good
- Committed new changes that are showing above

Please let me know if you need me to do anything else, thanks

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +| `control-plane.bridge.lookAndFeelUrl`                 | Specifies a [custom look and feel](https://github.com/keptn/keptn/tree/release-0.9.0/bridge#custom-look-and-feel) for Keptn Bridge
```suggestion
| `control-plane.bridge.lookAndFeelUrl`                 | Specifies a [custom look and feel](https://github.com/keptn/keptn/tree/release-0.10.0/bridge#custom-look-and-feel) for Keptn Bridge                | any URL containing a zip archive      | null                           |
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.9.0 --repo=https://storage.googleapis.com/keptn-installer --set=control-plane.apiGatewayNginx.type=LoadBalancer
```suggestion
helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.10.0 --repo=https://storage.googleapis.com/keptn-installer --set=control-plane.apiGatewayNginx.type=LoadBalancer
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.9.0 --repo=https://storage.googleapis.com/keptn-installer --set=continuous-delivery.enabled=true
```suggestion
helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.10.0 --repo=https://storage.googleapis.com/keptn-installer --set=continuous-delivery.enabled=true
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.9.0 --repo=https://storage.googleapis.com/keptn-installer --set=continuous-delivery.enabled=true,control-plane.apiGat
```suggestion
helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.10.0 --repo=https://storage.googleapis.com/keptn-installer --set=continuous-delivery.enabled=true,control-plane.apiGatewayNginx.type=LoadBalancer
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +curl -L https://github.com/keptn/keptn/releases/download/0.9.0/jmeter-service-0.9.0.tgz -o jmeter-service-0.9.0.tgz
```suggestion
curl -L https://github.com/keptn/keptn/releases/download/0.10.0/keptn-0.9.0.tgz -o keptn-0.10.0.tgz
curl -L https://github.com/keptn/keptn/releases/download/0.10.0/helm-service-0.9.0.tgz -o helm-service-0.10.0.tgz
curl -L https://github.com/keptn/keptn/releases/download/0.10.0/jmeter-service-0.9.0.tgz -o jmeter-service-0.10.0.tgz
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +KEPTN_TAG=0.9.0 ./pull_and_retag_images.sh "your-registry.localhost:5000/"
```suggestion
KEPTN_TAG=0.10.0 ./pull_and_retag_images.sh "your-registry.localhost:5000/"
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +./install_keptn.sh "your-registry.localhost:5000/" keptn-0.9.0.tgz helm-service-0.9.0.tgz jmeter-service-0.9.0.tgz
```suggestion
./install_keptn.sh "your-registry.localhost:5000/" keptn-0.10.0.tgz helm-service-0.10.0.tgz jmeter-service-0.10.0.tgz
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.9.0 --repo=https://storage.googleapis.com/keptn-installer --set=control-plane.apiGatewayNginx.type=LoadBalancer,conti
```suggestion
helm upgrade keptn keptn --install -n keptn --create-namespace --wait --version=0.10.0 --repo=https://storage.googleapis.com/keptn-installer --set=control-plane.apiGatewayNginx.type=LoadBalancer,continuous-delivery.enabled=true,control-plane.prefixPath=/mykeptn
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +* jmeter-service (if needed): https://github.com/keptn/keptn/releases/download/0.9.0/jmeter-service-0.9.0.tgz
```suggestion
* Keptn Control Plane: https://github.com/keptn/keptn/releases/download/0.10.0/keptn-0.10.0.tgz
* helm-service (if needed): https://github.com/keptn/keptn/releases/download/0.10.0/helm-service-0.10.0.tgz
* jmeter-service (if needed): https://github.com/keptn/keptn/releases/download/0.10.0/jmeter-service-0.10.0.tgz
```

2021-09-24 12:58 UTC, thisthat commented on content/docs/0.10.x/operate/advanced_install_options/index.md
> +Download the Helm charts from the [Keptn 0.9.0 release](https://github.com/keptn/keptn/releases/tag/0.9.0):
```suggestion
Download the Helm charts from the [Keptn 0.10.0 release](https://github.com/keptn/keptn/releases/tag/0.10.0):
```

2021-09-24 13:00 UTC, thisthat commented
Hi @bradmccoydev! Thank you for your help! I noticed a few lines which reference the wrong Keptn version. After these lines are fixed, we can merge this PR :shipit:

2021-09-25 00:52 UTC, bradmccoydev commented
Hey @thisthat. Great catch! I have made the changes, thank you!

2021-09-27 07:36 UTC, mowies commented
Hi @bradmccoydev !
Unofrtunetely there was some internal miscommunication which meant that I told you to rebase onto the wrong branch. If that's fine with you I will fix the issues with branching and folders on your branch directly and then we can merge this PR.

2021-09-27 08:04 UTC, bradmccoydev commented
Hey @mowies no problem, sounds good

2021-09-27 08:17 UTC, merged